//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektfeladat_z7kfuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competitor()
        {
            this.TableIntermediates = new HashSet<TableIntermediate>();
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public string CompetitorName { get; set; }
        public string WcaId { get; set; }
        public string Country { get; set; }
        public System.DateTime BirthDate { get; set; }
    
        public virtual Competition Competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableIntermediate> TableIntermediates { get; set; }
    }
}
