//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projektfeladat_z7kfuz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.TableIntermediates = new HashSet<TableIntermediate>();
        }
    
        public int Id { get; set; }
        public bool C222 { get; set; }
        public bool C333 { get; set; }
        public bool C444 { get; set; }
        public bool C555 { get; set; }
        public bool C666 { get; set; }
        public bool C777 { get; set; }
        public bool C333bld { get; set; }
        public bool C333fmc { get; set; }
        public bool C333oh { get; set; }
        public bool C333feet { get; set; }
        public bool Clock { get; set; }
        public bool Mega { get; set; }
        public bool Pyra { get; set; }
        public bool Skewb { get; set; }
        public bool Sq1 { get; set; }
        public bool C444bld { get; set; }
        public bool C555bld { get; set; }
        public bool Multibld { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableIntermediate> TableIntermediates { get; set; }
    }
}
